add plan
Li-Rui-QI/Intelligent-Placer pull request #2
Opened 2022-10-10 08:32 UTC by Li-Rui-QI

2022-10-14 15:56 UTC, DmitryjVeselyj commented on README.md
>  ## План решения
Возможно стоит добавить обработку особых случаев. Например, если сумма площадей предметов больше площади многоугольника, то мы сразу можем сказать, что разместить все предметы не получится

2022-10-14 15:56 UTC, DmitryjVeselyj commented on README.md
> +   3. Объединить объекты, границу многоугольника с внутренностью многоугольника
Не очень понятно, как Вы планируете размещать предметы в многоугольнике. Можно попробовать укладывать предметы с наибольшей границей соприкосновения.

P.S. Скорее всего, существует способ, как сделать это разумнее.Я предложил один из вариантов, который может быть полезен

2022-10-14 19:12 UTC, Li-Rui-QI commented on README.md
>  ## План решения
хорошо. добавил

2022-10-15 17:35 UTC, levs2001 requested changes
План алгоритма нужно доработать. Как минимум, добавить указание, по какому принципу объекты будут размещаться в многоугольнике. Также не хватает какого-то описание вычисления размеров объектов и многоугольника, нет описания структур данных, в которых это все будет храниться.

Если по моим комментам будут вопросы, то можешь писать тут или в вк: https://vk.com/levs2001

Если по части языка есть сложности, то сложные-непонятные моменты можем с тобой обсуждать на английском.

2022-10-15 17:35 UTC, levs2001 commented on README.md
>  Многоугольнику:
Ты неправильно pull reques сделал. Сюда не все коммиты попали. В  dev ветке 16 коммитов, здесь всего 4. Неудобно ревьюить, пришлось залезть в dev ветку и там смотреть.

2022-10-15 17:35 UTC, levs2001 commented on README.md
> +3. Многоугольник нарисован на чистом белом листе формата А4(если сумма площадей предметов больше площади многоугольника - не получится);
Про оптимизацию с площадью лучше написать в плане решения, а не в постановке.

2022-10-15 17:35 UTC, levs2001 commented on README.md
> +   4. Покрасить фон черным цветом,объект серым цветом 128,многоугольник белым цветом
Зачем эта покраска?

2022-10-15 17:35 UTC, levs2001 commented on README.md
>  4. Соберите результаты и представьте.
Что именно ты понимаешь под сбором и предоставлением результатов? Вывод "True" или "False"? Или что-то более объемное?

2022-10-15 17:35 UTC, levs2001 commented on README.md
> +   3. Объединить объекты, границу многоугольника с внутренностью многоугольника
Полностью согласен c @DmitryjVeselyj, по сути, в плане не написано самое главное - как размещать объекты в многоугольнике.

2022-10-22 16:44 UTC, Li-Rui-QI commented on README.md
>  4. Соберите результаты и представьте.
Я так понимаю что можно ли разместить объект в многоуголнике,если не может то False, иначе True

2022-10-22 16:46 UTC, Li-Rui-QI commented on README.md
> +   4. Покрасить фон черным цветом,объект серым цветом 128,многоугольник белым цветом
чтобы лучше различать границы, многоугольника и объекты

2022-10-22 16:46 UTC, Li-Rui-QI commented on README.md
> +3. Многоугольник нарисован на чистом белом листе формата А4(если сумма площадей предметов больше площади многоугольника - не получится);
хорошо

2022-10-22 16:48 UTC, Li-Rui-QI commented on README.md
>  Многоугольнику:
я первый раз сделать,  не очень опытный.прости

2022-10-22 16:49 UTC, Li-Rui-QI commented on README.md
> +   3. Объединить объекты, границу многоугольника с внутренностью многоугольника
да，буду дополнять алгоритм

2022-10-23 09:16 UTC, merged